# Generated by Django 5.2 on 2025-10-11 19:28

import ecommerce_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_product_reviews_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=ecommerce_app.models.product_image_upload_path),
        ),
    ]
