# Generated by Django 5.2 on 2025-10-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce_app', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='ecommerce_a_email_be4f65_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['activation_token'], name='ecommerce_a_activat_bcc8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_reset_token'], name='ecommerce_a_passwor_103ae3_idx'),
        ),
    ]
