# Generated by Django 5.2 on 2025-10-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_alter_order_options_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.CharField(blank=True, help_text='e.g., FedEx, UPS, DHL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Link to track the delivery', null=True),
        ),
    ]
