# Generated by Django 5.2 on 2025-11-08 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_order_actual_delivery_date_order_delivery_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
